export const ActionTypes = {
  SIGN_IN: "SIGN_IN",
  FETCH_POSTS: "FETCH_POSTS",
  SET_POSTS: "SET_POSTS",
  CREATE_POST: "CREATE_POST",
  FETCH_SUGGESTIONS: "FETCH_SUGGESTIONS",
  FETCH_PROFILE: "FETCH_PROFILE",
  DELETE_POST: "DELETE_POST",
  UPDATE_POST: "UPDATE_POST",
};
